version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: think-binlog-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: binlog_user
      MYSQL_PASSWORD: binlog_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - binlog-network

  redis:
    image: redis:7-alpine
    container_name: think-binlog-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - binlog-network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: think-binlog-php
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/html
    depends_on:
      - mysql
      - redis
    networks:
      - binlog-network
    tty: true

  nginx:
    image: nginx:alpine
    container_name: think-binlog-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - binlog-network

volumes:
  mysql_data:
  redis_data:

networks:
  binlog-network:
    driver: bridge
